@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User enters Available Command;

:AvailableCommandParser parses input;

if () then ([command is valid])
    :Creates an AvailableCommand with a  TutorialTagContainsGroupPredicate;
    if () then ([tutorial group exists])
        :Update FilterPersonList with the predicate;
    else ([else])
        :Display error message;
    endif
else ([command is invalid])
    :Display error message;
endif
stop
@enduml
